/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carrentalsystem;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.*;


public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    AddCustomer addcustomer = new AddCustomer();
    AddVehicle addvehicle = new AddVehicle();
    AddRental addrental = new AddRental();
    ReturnRental returnrental = new ReturnRental();
    SearchCustomer searchcustomer = new SearchCustomer();
    SearchVehicle searchvehicle = new SearchVehicle();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnaddcustomer = new javax.swing.JButton();
        btnaddvehicle = new javax.swing.JButton();
        btnaddrental = new javax.swing.JButton();
        btnreturnrental = new javax.swing.JButton();
        btnsearchcust = new javax.swing.JButton();
        btnsearchveh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnaddcustomer.setText("Add Customer");
        btnaddcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddcustomerActionPerformed(evt);
            }
        });

        btnaddvehicle.setText("Add Vehicle");
        btnaddvehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddvehicleActionPerformed(evt);
            }
        });

        btnaddrental.setText("Add Rental");
        btnaddrental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddrentalActionPerformed(evt);
            }
        });

        btnreturnrental.setText("Return Rental");
        btnreturnrental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturnrentalActionPerformed(evt);
            }
        });

        btnsearchcust.setText("Search Customer");
        btnsearchcust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchcustActionPerformed(evt);
            }
        });

        btnsearchveh.setText("Search Vehicle");
        btnsearchveh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchvehActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnsearchcust, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnaddrental, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnaddcustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnsearchveh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnaddvehicle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnreturnrental, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaddcustomer)
                    .addComponent(btnaddvehicle))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaddrental)
                    .addComponent(btnreturnrental))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsearchcust)
                    .addComponent(btnsearchveh))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddcustomerActionPerformed
        // TODO add your handling code here:
        addcustomer.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnaddcustomerActionPerformed

    private void btnaddvehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddvehicleActionPerformed
        // TODO add your handling code here:
        addvehicle.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnaddvehicleActionPerformed

    private void btnsearchcustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchcustActionPerformed
        // TODO add your handling code here:
        searchcustomer.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnsearchcustActionPerformed

    private void btnsearchvehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchvehActionPerformed
        // TODO add your handling code here:
        searchvehicle.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnsearchvehActionPerformed

    private void btnaddrentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddrentalActionPerformed
        // TODO add your handling code here:
        addrental.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnaddrentalActionPerformed

    private void btnreturnrentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturnrentalActionPerformed
        // TODO add your handling code here:
        returnrental.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnreturnrentalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddcustomer;
    private javax.swing.JButton btnaddrental;
    private javax.swing.JButton btnaddvehicle;
    private javax.swing.JButton btnreturnrental;
    private javax.swing.JButton btnsearchcust;
    private javax.swing.JButton btnsearchveh;
    // End of variables declaration//GEN-END:variables
}
