/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carrentalsystem;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ReturnRental extends javax.swing.JFrame {

    /**
     * Creates new form ReturnRental
     */
    public ReturnRental() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        // preset combobox
        Connection con = null;
        PreparedStatement ps = null;
        
        try{
            String driver = "com.mysql.jdbc.Driver";
            String url = "jdbc:mysql://localhost:3306/carrentalsystem";
            String username = "root";
            String password = "";
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(url,username,password);
            Statement stmt = con.createStatement();
            
            String sql = "SELECT DISTINCT v.VehicleID, v.Description FROM Vehicle v, Rental r WHERE v.VehicleID = r.VehicleID and Returned = '0'";
            ResultSet rs = stmt.executeQuery(sql);
            int n=0,i=0;
            while(rs.next())
            {
                n++;
            } 
            String[] cars = new String[n];
            rs = stmt.executeQuery(sql);
            while(rs.next())
            {
                cars[i]=rs.getString(2);
                i++;
            }
            DefaultComboBoxModel model = new DefaultComboBoxModel(cars);
            cbvehinfo.setModel( model );

        } catch(Exception e) {
            e.printStackTrace();
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfreturnrentalreturndate = new javax.swing.JTextField();
        tfreturnrentalphone = new javax.swing.JTextField();
        btnreturnrentalsearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        returnrentaltable = new javax.swing.JTable();
        returnrentalpaydue = new javax.swing.JButton();
        gohome = new javax.swing.JButton();
        cbvehinfo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Return Date *");

        jLabel2.setText("Phone Number *");

        jLabel3.setText("Vehicle Info");

        btnreturnrentalsearch.setText("Search");
        btnreturnrentalsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturnrentalsearchActionPerformed(evt);
            }
        });

        returnrentaltable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Phone", "Return Date", "Total Due"
            }
        ));
        jScrollPane1.setViewportView(returnrentaltable);

        returnrentalpaydue.setText("Pay Due");
        returnrentalpaydue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnrentalpaydueActionPerformed(evt);
            }
        });

        gohome.setText("Home");
        gohome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gohomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 120, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfreturnrentalreturndate, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfreturnrentalphone)
                                .addComponent(cbvehinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(btnreturnrentalsearch))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(gohome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(returnrentalpaydue)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gohome)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfreturnrentalreturndate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfreturnrentalphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbvehinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnreturnrentalsearch)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(returnrentalpaydue)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnreturnrentalsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturnrentalsearchActionPerformed
        // TODO add your handling code here:
        
        String phonenumeber = tfreturnrentalphone.getText();
        String returndate = tfreturnrentalreturndate.getText();
        if(phonenumeber.length()==0 || returndate.length()==0){
            JOptionPane.showMessageDialog(null, "Please fill up all fields");
        } else {
            Connection con = null;
            PreparedStatement ps = null;

            try{
                String driver = "com.mysql.jdbc.Driver";
                String url = "jdbc:mysql://localhost:3306/carrentalsystem";
                String username = "root";
                String password = "";
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(url,username,password);
                Statement stmt = con.createStatement();

                String sql = "SELECT DISTINCT v.VehicleID, v.Description FROM Vehicle v, Rental r WHERE v.VehicleID = r.VehicleID and Returned = '0'";
                ResultSet rs = stmt.executeQuery(sql);
                String selectedmodel =cbvehinfo.getSelectedItem().toString();


                String vehid="";
                String sql2= "SELECT v.VehicleID FROM Vehicle v, rental r WHERE v.VehicleID = r.VehicleID and v.Description = '"+selectedmodel+"' and r.ReturnDate = '"+returndate+"';";
                ResultSet rs2 = stmt.executeQuery(sql2);
                while(rs2.next())
                {
                    vehid=rs2.getString(1);
                    System.out.println(rs2.getString(1));
                }
                String custid="";
                String sql3= " SELECT CustID FROM Customer WHERE Phone = '"+phonenumeber+"'";
                ResultSet rs3 = stmt.executeQuery(sql3);
                while(rs3.next())
                {
                    custid=rs3.getString(1);
                }
                String sql4="SELECT c.Name as 'Name', c.Phone as 'Phone', r.ReturnDate as'ReturnDate', SUM(r.TotalAmount) as 'PaymentDue'FROM customer c, rental r , Vehicle v WHERE c.CustID = '"+custid+"' and c.CustID = r.CustID and r.VehicleID= v.VehicleID and v.VehicleID = '"+vehid+"'";
                ResultSet rs4 = stmt.executeQuery(sql4);
                DefaultTableModel tblmodel=(DefaultTableModel)returnrentaltable.getModel();
                while(rs4.next())
                {
                    String data[]={rs4.getString(1),rs4.getString(2),rs4.getString(3),rs4.getString(4)};
                    tblmodel.addRow(data);
                }
            } catch(Exception e) {
                e.printStackTrace();
            } 
        }
        
    }//GEN-LAST:event_btnreturnrentalsearchActionPerformed

    private void returnrentalpaydueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnrentalpaydueActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        PreparedStatement ps = null;
        
        try{
            String driver = "com.mysql.jdbc.Driver";
            String url = "jdbc:mysql://localhost:3306/carrentalsystem";
            String username = "root";
            String password = "";
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(url,username,password);
            Statement stmt = con.createStatement();
            
            String sql = "SELECT DISTINCT v.VehicleID, v.Description FROM Vehicle v, Rental r WHERE v.VehicleID = r.VehicleID and Returned = '0'";
            ResultSet rs = stmt.executeQuery(sql);
            String selectedmodel =cbvehinfo.getSelectedItem().toString();

            
            String phonenumeber = tfreturnrentalphone.getText();
            String returndate = tfreturnrentalreturndate.getText();
            String vehid="";
            String sql2= "SELECT v.VehicleID FROM Vehicle v, rental r WHERE v.VehicleID = r.VehicleID and v.Description = '"+selectedmodel+"' and r.ReturnDate = '"+returndate+"';";
            ResultSet rs2 = stmt.executeQuery(sql2);
            while(rs2.next())
            {
                vehid=rs2.getString(1);
                System.out.println(rs2.getString(1));
            }
            String custid="";
            String sql3= " SELECT CustID FROM Customer WHERE Phone = '"+phonenumeber+"'";
            ResultSet rs3 = stmt.executeQuery(sql3);
            while(rs3.next())
            {
                custid=rs3.getString(1);
            }
            String sql4="SELECT c.Name as 'Name', c.Phone as 'Phone', r.ReturnDate as'ReturnDate', SUM(r.TotalAmount) as 'PaymentDue'FROM customer c, rental r , Vehicle v WHERE c.CustID = '"+custid+"' and c.CustID = r.CustID and r.VehicleID= v.VehicleID and v.VehicleID = '"+vehid+"'";
            ResultSet rs4 = stmt.executeQuery(sql4);
            int due=0;
            while(rs4.next())
            {
                due=Integer.parseInt(rs4.getString(4));
            }
            if(due==0)
            {
                String query = "UPDATE rental SET Returned = '1' WHERE CustID = ? and ReturnDate = ? and VehicleID = ?";
                ps = con.prepareStatement(query);
                ps.setString (1, custid);
                ps.setString (2, returndate);
                ps.setString (3, vehid);
                System.out.println(ps);
                int i = ps.executeUpdate();
                if (i > 0) {
                    JOptionPane.showMessageDialog(null, "Vecihle returned!");
                } else {
                    JOptionPane.showMessageDialog(null, "Failed");
                }
            } 
            else 
            {
                String query = "UPDATE rental SET Returned = '1', TotalAmount = '0' WHERE CustID = ? and ReturnDate = ? and VehicleID = ?";
                ps = con.prepareStatement(query);
                ps.setString (1, custid);
                ps.setString (2, returndate);
                ps.setString (3, vehid);
                System.out.println(ps);
                int i = ps.executeUpdate();
                if (i > 0) {
                    JOptionPane.showMessageDialog(null, "Payment successful");
                } else {
                    JOptionPane.showMessageDialog(null, "Failed");
                }
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
       
    }//GEN-LAST:event_returnrentalpaydueActionPerformed

    private void gohomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gohomeActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gohomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnRental().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnreturnrentalsearch;
    private javax.swing.JComboBox<String> cbvehinfo;
    private javax.swing.JButton gohome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton returnrentalpaydue;
    private javax.swing.JTable returnrentaltable;
    private javax.swing.JTextField tfreturnrentalphone;
    private javax.swing.JTextField tfreturnrentalreturndate;
    // End of variables declaration//GEN-END:variables
}
